# -*- coding: utf-8 -*-
"""CreateDepthMap

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uuKey4Q-ShnT3oE4Ttrh8PVJC7_SxG6J
"""

import cv2
import matplotlib
from matplotlib import pyplot as plt

imgL = cv2.imread('./Left.png',0)
imgR = cv2.imread('./Right.png',0)

stereo = cv2.StereoBM_create(16, 15)
disparity = stereo.compute(imgL, imgR)

plt.imshow(disparity, 'gray')

cv2.imwrite('./disparity.png', disparity )

